name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * 1" # runs every Monday
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: pruthviiraj
          outputs: dist/snake.svg
      - name: Commit snake
        run: |
          rm -rf output
          mkdir -p output
          cp dist/snake.svg output/github-contribution-grid-snake.svg
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update snake"
          git branch -M output
          git remote add origin https://github.com/pruthviiraj/pruthviiraj.git
          git push -f origin output
          chore: add snake animation workflow
